<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="duankj-book" name="com.testing.runner.dataDrivenOfInter1" tests="9" failures="3" timestamp="26 二月 2020 10:25:11 GMT" time="1.713" errors="0">
  <testcase name="f" time="0.645" classname="com.testing.runner.dataDrivenOfInter1">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [{&quot;total&quot;:140,&quot;alarm&quot;:18,&quot;online&quot;:3,&quot;active&quot;:38,&quot;disabled&quot;:1,&quot;error&quot;:3}]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [{"total":140,"alarm":18,"online":3,"active":38,"disabled":1,"error":3}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testing.runner.dataDrivenOfInter1.f(dataDrivenOfInter1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.107" classname="com.testing.runner.dataDrivenOfInter1"/>
  <testcase name="f" time="0.008" classname="com.testing.runner.dataDrivenOfInter1"/>
  <testcase name="f" time="0.094" classname="com.testing.runner.dataDrivenOfInter1">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [fail]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [fail]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testing.runner.dataDrivenOfInter1.f(dataDrivenOfInter1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.002" classname="com.testing.runner.dataDrivenOfInter1"/>
  <testcase name="f" time="0.078" classname="com.testing.runner.dataDrivenOfInter1"/>
  <testcase name="f" time="0.028" classname="com.testing.runner.dataDrivenOfInter1">
    <failure type="java.lang.AssertionError" message="expected [pass] but found [{&quot;id&quot;:{&quot;entityType&quot;:&quot;ASSET&quot;,&quot;id&quot;:&quot;3e7bd6e0-56c9-11ea-b268-7fba5b302469&quot;},&quot;createdTime&quot;:1582523292494,&quot;additionalInfo&quot;:null,&quot;tenantId&quot;:{&quot;entityType&quot;:&quot;TENANT&quot;,&quot;id&quot;:&quot;25453870-a9bc-11e9-be21-f7760de09a70&quot;},&quot;projectId&quot;:{&quot;entityType&quot;:&quot;PROJECT&quot;,&quot;id&quot;:&quot;13814000-1dd2-11b2-8080-808080808080&quot;},&quot;name&quot;:&quot;Saas资产关联的设备API&quot;,&quot;type&quot;:&quot;1&quot;,&quot;infos&quot;:[{&quot;from&quot;:{&quot;entityType&quot;:&quot;ASSET&quot;,&quot;id&quot;:&quot;3e7bd6e0-56c9-11ea-b268-7fba5b302469&quot;},&quot;to&quot;:{&quot;entityType&quot;:&quot;ASSET&quot;,&quot;id&quot;:&quot;92e04d10-56c9-11ea-b947-d30eb9346ed1&quot;},&quot;type&quot;:&quot;Contains&quot;,&quot;typeGroup&quot;:&quot;COMMON&quot;,&quot;additionalInfo&quot;:null,&quot;fromName&quot;:null,&quot;toName&quot;:&quot;被关联从&quot;}]}]">
      <![CDATA[java.lang.AssertionError: expected [pass] but found [{"id":{"entityType":"ASSET","id":"3e7bd6e0-56c9-11ea-b268-7fba5b302469"},"createdTime":1582523292494,"additionalInfo":null,"tenantId":{"entityType":"TENANT","id":"25453870-a9bc-11e9-be21-f7760de09a70"},"projectId":{"entityType":"PROJECT","id":"13814000-1dd2-11b2-8080-808080808080"},"name":"Saas资产关联的设备API","type":"1","infos":[{"from":{"entityType":"ASSET","id":"3e7bd6e0-56c9-11ea-b268-7fba5b302469"},"to":{"entityType":"ASSET","id":"92e04d10-56c9-11ea-b947-d30eb9346ed1"},"type":"Contains","typeGroup":"COMMON","additionalInfo":null,"fromName":null,"toName":"被关联从"}]}]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.testing.runner.dataDrivenOfInter1.f(dataDrivenOfInter1.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- f -->
  <testcase name="f" time="0.749" classname="com.testing.runner.dataDrivenOfInter1"/>
  <testcase name="f" time="0.002" classname="com.testing.runner.dataDrivenOfInter1"/>
</testsuite> <!-- com.testing.runner.dataDrivenOfInter1 -->
